name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Make build environment
      run: mkdir -p build/out

    - name: Run CMake
      run: cmake -D CMAKE_RUNTIME_OUTPUT_DIRECTORY=./out/ ..
      working-directory: ./build/

    - name: Build project
      run: make
      working-directory: ./build/

    - name: Move executable
      run: mv build/out/$(ls build/out | head -n 1) ./submission

    - name: Get test files
      run: |
        wget https://raw.githubusercontent.com/UWM-COMPSCI458/PA1M1_grader/refs/heads/main/tester.sh
        wget https://github.com/UWM-COMPSCI458/PA1M1_grader/raw/refs/heads/main/reference
        chmod +x reference

    - name: Run tests
      uses: UWM-COMPSCI458/autograding-command-grader@main
      id: pa1m1-tests
      continue-on-error: true
      with:
        test-name: PA1M1 Tests
        command: "bash"
        arguments: '["./tester.sh", "./reference", "./submission"]'
        timeout: 10
        max-score: 75
